import {expensePie} from './financeiro-pie.js';
import {ROBLEDO_ID,categories,today,effectiveDate,summarize,isOverdue} from './financeiro-model.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const date=v=>v?.split('-').reverse().join('/')||'—';
const options=(items,value)=>items.map(v=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(v)}</option>`).join('');
export async function financePage({db,el,profile,back}){
 if(profile.id!==ROBLEDO_ID){el.innerHTML='<p role="alert">Acesso não autorizado.</p>';return}
 let rows=[],month=today().slice(0,7),type='',status='',query='';
 async function load(){el.innerHTML='<p role="status">Carregando controle financeiro…</p>';rows=[];for(let start=0;;start+=500){const {data,error}=await db.from('financeiro_f8').select('*').order('vencimento',{ascending:false}).order('id').range(start,start+499);if(error){el.innerHTML='<p role="alert">Não foi possível carregar o financeiro.</p><button id="retryFinance">Tentar novamente</button>';el.querySelector('button').onclick=load;return}rows.push(...data);if(data.length<500)break}render()}
 function render(){const s=summarize(rows,month),filtered=rows.filter(r=>(!month||effectiveDate(r)?.startsWith(month))&&(!type||r.tipo===type)&&(!status||(status==='atrasado'?isOverdue(r):r.status===status))&&(`${r.descricao} ${r.pessoa} ${r.categoria} ${r.subcategoria}`.toLowerCase().includes(query.toLowerCase())));const months=Array.from({length:6},(_,i)=>{const [y,m]=month.split('-').map(Number),d=new Date(Date.UTC(y,m-6+i,1)),key=d.toISOString().slice(0,7);return {key,...summarize(rows,key)}}),max=Math.max(1,...months.flatMap(m=>[m.entrada,m.saida]));
 el.innerHTML=`<div class="welcome"><div><h1>Controle financeiro</h1><p class="muted">Entradas, saídas e compromissos da F8</p></div><div class="actions"><button class="ghost" id="financeBack">Áreas</button><button id="newIncome">+ Entrada</button><button id="newExpense">+ Saída</button></div></div>
 <label class="financeMonth">Mês de referência<input id="financeMonth" type="month" required value="${month}"></label>
 <div class="cards financeCards">${[['Entradas recebidas',s.entrada,'income','entrada','liquidado'],['Saídas pagas',s.saida,'expense','saida','liquidado'],['Resultado do mês',s.resultado,''],['A receber no mês',s.receber,'','entrada','pendente'],['A pagar no mês',s.pagar,'','saida','pendente'],['Saldo dos lançamentos',s.saldo,'']].map(([label,value,cls,filterType,filterStatus])=>`<article class="${cls}" ${filterType?`role="button" tabindex="0" data-finance-type="${filterType}" data-finance-status="${filterStatus}" aria-label="${label}: ver lançamentos do mês corrente"`:""}><b>${money(value)}</b><span>${label}</span></article>`).join('')}</div><p class="muted">Saldo acumulado de todos os lançamentos liquidados. Cadastre o saldo inicial como entrada ou saída na categoria Outras. Não inclui valores pendentes.</p>
 <section class="financeChart"><h2>Entradas e saídas — últimos 6 meses</h2><p><span class="income">■ Entradas recebidas</span> · <span class="expense">■ Saídas pagas</span></p><div class="financeBars" role="img" aria-label="Comparação mensal de entradas recebidas e saídas pagas">${months.map(m=>`<div class="financeBarGroup"><div class="financePair"><div class="incomeBar" style="height:${m.entrada/max*160}px" title="Entradas: ${money(m.entrada)}"></div><div class="expenseBar" style="height:${m.saida/max*160}px" title="Saídas: ${money(m.saida)}"></div></div><b>${m.key.slice(5)}/${m.key.slice(2,4)}</b><span class="income">${money(m.entrada)}</span><span class="expense">${money(m.saida)}</span></div>`).join('')}</div></section>
 ${expensePie(rows,month)}
 <section id="financeEntries"><h2>Lançamentos</h2><div class="financeFilters"><label>Buscar<input id="financeSearch" value="${esc(query)}" placeholder="Descrição, pessoa ou categoria"></label><label>Tipo<select id="financeType"><option value="">Todos</option>${options(['entrada','saida'],type)}</select></label><label>Situação<select id="financeStatus"><option value="">Todas</option>${options(['pendente','liquidado','cancelado','atrasado'],status)}</select></label></div><p class="muted">Recebidos e pagos são filtrados pela data de pagamento; pendentes e cancelados, pelo vencimento.</p><div>${filtered.map(r=>`<article class="row financeRow"><div><b>${esc(r.descricao)}</b><span>${esc(r.pessoa||'Sem cliente / fornecedor')} · ${esc(r.categoria)} / ${esc(r.subcategoria)}</span><span>Vencimento: ${date(r.vencimento)}${r.data_pagamento?' · Liquidação: '+date(r.data_pagamento):''} · ${isOverdue(r)?'<strong class="expense">Em atraso</strong>':r.status==='liquidado'?(r.tipo==='entrada'?'Recebido':'Pago'):esc(r.status)}</span></div><div class="actions"><strong class="${r.tipo==='entrada'?'income':'expense'}">${r.tipo==='entrada'?'+':'−'} ${money(r.valor)}</strong><button class="ghost" data-edit-finance="${r.id}">Editar</button></div></article>`).join('')||'<p class="notice">Nenhum lançamento neste filtro. Cadastre uma entrada ou saída para começar.</p>'}</div></section>`;
 el.querySelectorAll('[data-finance-type]').forEach(card=>{const apply=()=>{month=today().slice(0,7);type=card.dataset.financeType;status=card.dataset.financeStatus;query='';render();const section=el.querySelector('#financeEntries');section.scrollIntoView?.({behavior:'smooth',block:'start'});el.querySelector('#financeType').focus({preventScroll:true})};card.onclick=apply;card.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();apply()}}});
 el.querySelector('#financeBack').onclick=back;el.querySelector('#newIncome').onclick=()=>form({tipo:'entrada'});el.querySelector('#newExpense').onclick=()=>form({tipo:'saida'});
 el.querySelector('#financeMonth').onchange=e=>{if(e.target.value){month=e.target.value;render()}};el.querySelector('#financeType').onchange=e=>{type=e.target.value;render()};el.querySelector('#financeStatus').onchange=e=>{status=e.target.value;render()};el.querySelector('#financeSearch').oninput=e=>{query=e.target.value;render();const input=el.querySelector('#financeSearch');input.focus();input.setSelectionRange(query.length,query.length)};el.querySelectorAll('[data-edit-finance]').forEach(b=>b.onclick=()=>form(rows.find(r=>r.id===b.dataset.editFinance)));
 }
 function form(r){r={descricao:'',valor:'',categoria:'',subcategoria:'',pessoa:'',vencimento:today(),status:'pendente',data_pagamento:'',forma_pagamento:'Pix',conta:'',observacoes:'',...r};const fresh=!r.id;
 el.innerHTML=`<div class="welcome"><h1>${fresh?'Nova':'Editar'} ${r.tipo==='entrada'?'entrada':'saída'}</h1><button class="ghost" id="cancelFinance">Voltar</button></div><form id="financeForm"><div class="form"><label>Descrição<input name="descricao" required maxlength="250" value="${esc(r.descricao)}"></label><label>Valor (R$)<input name="valor" type="number" step="0.01" min="0.01" max="9999999999.99" required value="${r.valor}"></label><label>Categoria<select name="categoria" required></select></label><label>Subcategoria<select name="subcategoria" required></select></label><label>Cliente / Fornecedor<input name="pessoa" maxlength="250" list="financePeople" value="${esc(r.pessoa)}"><datalist id="financePeople">${[...new Set(rows.map(r=>r.pessoa).filter(Boolean))].map(v=>`<option value="${esc(v)}">`).join('')}</datalist></label><label>Vencimento<input name="vencimento" type="date" required value="${r.vencimento}"></label><label>Situação<select name="status">${options(['pendente','liquidado','cancelado'],r.status)}</select></label><label id="paidDateLabel">Data do recebimento / pagamento<input name="data_pagamento" type="date" value="${r.data_pagamento}"></label><label>Forma de pagamento<select name="forma_pagamento">${options(['Pix','Dinheiro','Débito','Crédito','Boleto','Transferência','Outro'],r.forma_pagamento)}</select></label><label>Conta / Caixa<input name="conta" maxlength="150" placeholder="Ex.: Banco do Brasil ou caixa" value="${esc(r.conta)}"></label><label class="wide">Observações<textarea name="observacoes" maxlength="5000">${esc(r.observacoes)}</textarea></label></div><div class="actions">${fresh?'':'<button type="button" class="danger" id="deleteFinance">Excluir</button>'}<button id="saveFinance">Salvar lançamento</button></div><p id="financeMessage" role="alert"></p></form>`;
 const f=el.querySelector('form'),cat=f.elements.categoria,sub=f.elements.subcategoria,msg=el.querySelector('#financeMessage');cat.innerHTML=options(Object.keys(categories[r.tipo]),r.categoria);const updateSub=()=>{sub.innerHTML=options(categories[r.tipo][cat.value],r.subcategoria)};updateSub();cat.onchange=updateSub;const updatePaid=()=>{const paid=f.elements.status.value==='liquidado';el.querySelector('#paidDateLabel').hidden=!paid;f.elements.data_pagamento.required=paid;if(paid&&!f.elements.data_pagamento.value)f.elements.data_pagamento.value=today()};updatePaid();f.elements.status.onchange=updatePaid;el.querySelector('#cancelFinance').onclick=render;
 f.onsubmit=async e=>{e.preventDefault();const button=el.querySelector('#saveFinance');button.disabled=true;msg.textContent='';const v=Object.fromEntries(new FormData(f));v.tipo=r.tipo;v.valor=Number(v.valor);v.descricao=v.descricao.trim();v.pessoa=v.pessoa.trim();v.data_pagamento=v.status==='liquidado'?v.data_pagamento:null;if(!v.descricao||!Number.isFinite(v.valor)||v.valor<=0){msg.textContent='Preencha a descrição e um valor maior que zero.';button.disabled=false;return}const result=await (fresh?db.from('financeiro_f8').insert(v):db.from('financeiro_f8').update(v).eq('id',r.id)).select().single();if(result.error){msg.textContent='Não foi possível salvar. Verifique sua conexão e tente novamente.';button.disabled=false;return}await load()};if(!fresh)el.querySelector('#deleteFinance').onclick=async()=>{if(!confirm('Excluir este lançamento financeiro? Esta ação altera os totais.'))return;const button=el.querySelector('#deleteFinance');button.disabled=true;const result=await db.from('financeiro_f8').delete().eq('id',r.id).select('id').single();if(result.error){msg.textContent='Não foi possível excluir. Tente novamente.';button.disabled=false;return}await load()};
 }
 await load();
}
